export default {
  global: {
    colors: {
      /* Branding */
      brand: '#1b1b25',
      search: '#265C83',
      /* Backgrounds */
      bg_navy: '#001F3F',
      bg_blue: '#0074D9',
      bg_aqua: '#7FDBFF',
      bg_teal: '#39CCCC',
      bg_olive: '#3D9970',
      bg_green: '#2ECC40',
      bg_lime: '#01FF70',
      bg_yellow: '#FFDC00',
      bg_orange: '#FF851B',
      bg_red: '#FF4136',
      bg_fuchsia: '#F012BE',
      bg_purple: '#B10DC9',
      bg_maroon: '#85144B',
      bg_white: '#FFFFFF',
      bg_gray: '#AAAAAA',
      bg_silver: '#6D6D6D',
      bg_black: '#111111',
      /* Colors */
      navy: '#001F3F',
      blue: '#0074D9',
      aqua: '#7FDBFF',
      teal: '#39CCCC',
      olive: '#3D9970',
      green: '#2ECC40',
      lime: '#01FF70',
      yellow: '#FFDC00',
      orange: '#FF851B',
      red: '#FF4136',
      fuchsia: '#F012BE',
      purple: '#B10DC9',
      maroon: '#85144B',
      white: '#FFFFFF',
      silver: '#DDDDDD',
      gray: '#A2AAAA',
      black: '#111111',
      /* Border colors 
   Use with another border utility that sets border-width and style 
   i.e .border { border-width: 1px); border-style: solid); }
   */
      border_navy: '#001F3F',
      border_blue: '#0074D9',
      border_aqua: '#7FDBFF',
      border_teal: '#39CCCC',
      border_olive: '#3D9970',
      border_green: '#2ECC40',
      border_lime: '#01FF70',
      border_yellow: '#FFDC00',
      border_orange: '#FF851B',
      border_red: '#FF4136',
      border_fuchsia: '#F012BE',
      border_purple: '#B10DC9',
      border_maroon: '#85144B',
      border_white: '#FFFFFF',
      border_gray: '#AAAAAA',
      border_silver: '#DDDDDD',
      border_black: '#111111',
      /* Fills for SVG */
      fill_navy: '#001F3F',
      fill_blue: '#0074D9',
      fill_aqua: '#7FDBFF',
      fill_teal: '#39CCCC',
      fill_olive: '#3D9970',
      fill_green: '#2ECC40',
      fill_lime: '#01FF70',
      fill_yellow: '#FFDC00',
      fill_orange: '#FF851B',
      fill_red: '#FF4136',
      fill_fuchsia: '#F012BE',
      fill_purple: '#B10DC9',
      fill_maroon: '#85144B',
      fill_white: '#FFFFFF',
      fill_gray: '#26262A',
      fill_silver: '#DDDDDD',
      fill_black: '#111111',
      /* Strokes for SVG */
      stroke_navy: '#001F3F',
      stroke_blue: '#0074D9',
      stroke_aqua: '#7FDBFF',
      stroke_teal: '#39CCCC',
      stroke_olive: '#3D9970',
      stroke_green: '#2ECC40',
      stroke_lime: '#01FF70',
      stroke_yellow: '#FFDC00',
      stroke_orange: '#FF851B',
      stroke_red: '#FF4136',
      stroke_fuchsia: '#F012BE',
      stroke_purple: '#B10DC9',
      stroke_maroon: '#85144B',
      stroke_white: '#FFFFFF',
      stroke_gray: '#AAAAAA',
      stroke_silver: '#DDDDDD',
      stroke_black: '#111111',
    }
  }
}
